### ISSUE TITLE
Bring (experimental) Synapse support for delegated auth to an official release

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#15573]
This issue has been migrated from [#15573](https://github.com/matrix-org/synapse/issues/15573).

---

* [x] Admin API to provision users: https://github.com/matrix-org/synapse/pull/15611
* [x] Initial delegation support: https://github.com/matrix-org/synapse/pull/15582
* [ ] Synapse reverse proxying to the auth server

We'll eventually want some follow-ups too:

* [ ] Appservice support
* [ ] Documentation
* [ ] Better configuration errors
* [ ] Handle TODO comments
