### ISSUE TITLE
Declare support for Matrix v1.11

### ISSUE THREAD

**Issue by turt2live** [element-hq/synapse#17402]
Previous version: https://github.com/element-hq/synapse/issues/17021
Changelog (with clarifications included): https://spec.matrix.org/v1.11/changelog/#v111

### Client-Server API

**Deprecations**

- [x] Authentication using a query string is now deprecated, as per [MSC4126](https://github.com/matrix-org/matrix-spec-proposals/issues/4126). The `Authorization` header should be used instead. ([#1808](https://github.com/matrix-org/matrix-spec/issues/1808))
  - No-op
- [x] Use of the `/_matrix/media/*` endpoints is now deprecated. New, authenticated, endpoints are available instead. ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - See below

**New Endpoints**

- [x] [`GET /_matrix/client/v1/media/config`](/client-server-api/#get_matrixclientv1mediaconfig) ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - Made stable in https://github.com/element-hq/synapse/pull/17388
  - https://github.com/element-hq/synapse/pull/17213
- [x] [`GET /_matrix/client/v1/media/download/{serverName}/{mediaId}`](/client-server-api/#get_matrixclientv1mediadownloadservernamemediaid) ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - https://github.com/element-hq/synapse/pull/17365
- [x] [`GET /_matrix/client/v1/media/download/{serverName}/{mediaId}/{fileName}`](/client-server-api/#get_matrixclientv1mediadownloadservernamemediaidfilename) ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - https://github.com/element-hq/synapse/pull/17365
- [x] [`GET /_matrix/client/v1/media/preview_url`](/client-server-api/#get_matrixclientv1mediapreview_url) ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - Made stable in https://github.com/element-hq/synapse/pull/17388
  - https://github.com/element-hq/synapse/pull/17213
- [x] [`GET /_matrix/client/v1/media/thumbnail/{serverName}/{mediaId}`](/client-server-api/#get_matrixclientv1mediathumbnailservernamemediaid) ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - https://github.com/element-hq/synapse/pull/17388
  - https://github.com/element-hq/synapse/pull/17213

**Backwards Compatible Changes**

- [x] Add support for muting in VoIP calls, as per [MSC3291](https://github.com/matrix-org/matrix-spec-proposals/pull/3291). ([#1755](https://github.com/matrix-org/matrix-spec/issues/1755))
  - No-op (event change)
- [ ] Add optional `animated` query string option to `GET /thumbnail`, as per [MSC2705](https://github.com/matrix-org/matrix-spec-proposals/pull/2705). ([#1757](https://github.com/matrix-org/matrix-spec/issues/1757))
  - The MSC has provision for servers which don't support animation, so we're compliant here. Future support would be https://github.com/element-hq/synapse/issues/1278
- [x] Specify terms of services at registration, as per [MSC1692](https://github.com/matrix-org/matrix-spec-proposals/pull/1692). ([#1812](https://github.com/matrix-org/matrix-spec/issues/1812))
  - Support has been in Synapse forever
- [x] Add support for mathematical messages, as per [MSC2191](https://github.com/matrix-org/matrix-spec-proposals/pull/2191). ([#1816](https://github.com/matrix-org/matrix-spec/issues/1816))
  - No-op (client markup)
- [x] Do not require UIA when first uploading cross-signing keys, as per [MSC3967](https://github.com/matrix-org/matrix-spec-proposals/pull/3967). ([#1828](https://github.com/matrix-org/matrix-spec/issues/1828))
  - https://github.com/matrix-org/synapse/pull/15077
  - Made stable in https://github.com/element-hq/synapse/pull/17284
- [x] Add the new `unsigned.membership` property to events, as per [MSC4115](https://github.com/matrix-org/matrix-spec-proposals/pull/4115). ([#1847](https://github.com/matrix-org/matrix-spec/issues/1847))
  - https://github.com/element-hq/synapse/pull/17104
  - Made stable in https://github.com/element-hq/synapse/pull/17282
- [x] Media downloads and thumbnails are now authenticated, as per [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/pull/3916). ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - See above
- [x] Some media endpoints are now consistently under `/_matrix/client/{version}/media/*` instead of `/_matrix/media/*`, as per [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/pull/3916). ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - See above

### Server-Server API

**Deprecations**

- [x] Use of the Client-Server API `/_matrix/media/*` endpoints is now deprecated. New, authenticated, endpoints are available instead. ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - Fallback handled in https://github.com/element-hq/synapse/pull/17365

**New Endpoints**

- [x] [`GET /_matrix/federation/v1/media/download/{mediaId}`](/server-server-api/#get_matrixfederationv1mediadownloadmediaid) ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - Made stable in https://github.com/element-hq/synapse/pull/17365
  - Chain from https://github.com/element-hq/synapse/pull/17350
- [x] [`GET /_matrix/federation/v1/media/thumbnail/{mediaId}`](/server-server-api/#get_matrixfederationv1mediathumbnailmediaid) ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858))
  - https://github.com/element-hq/synapse/pull/17388

**Backwards Compatible Changes**

- [x] Media downloads and thumbnails are now authenticated, as per [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/pull/3916). ([#1858](https://github.com/matrix-org/matrix-spec/issues/1858), [#1869](https://github.com/matrix-org/matrix-spec/issues/1869))
  - See above

### Identity Service API

**Deprecations**

- [x] Authentication using a query string is now deprecated, as per [MSC4126](https://github.com/matrix-org/matrix-spec-proposals/issues/4126). The `Authorization` header should be used instead. ([#1808](https://github.com/matrix-org/matrix-spec/issues/1808))
  - No-op (all call sites I could find use the `Authorization` header already)
