### ISSUE TITLE
Implement MSC2326 (Label based filtering)

### ISSUE THREAD

**Issue by matrixbot** [element-hq/synapse#6288]
This issue has been migrated from [#6288](https://github.com/matrix-org/synapse/issues/6288).

---

Implement https://github.com/matrix-org/matrix-doc/pull/2326 in Synapse

PRs:

- [x] #6301 (basic support)
- [x] #6310 (background job to support previous events)
- [x] #6329 (support on `/context`, also on `/search` and some test refactoring)
- [x] #6340 (fix SQL used to query events when paginating)
- [ ] Support edits (was #6374)
